:date: 2016-07-25

=====================
Monday, July 25, 2016
=====================

When running a command on all projects using :cmd:`per_project`, then
it was no longer possible to run commands with arguments.  For
example::

    $ pp inv ci --today 20160724
    usage: per_project [-h] [-s START] [-u UNTIL] [cmd [cmd ...]]
    per_project: error: unrecognized arguments: --today 20160724

This was a case for `nargs=argparse.REMAINDER
<https://docs.python.org/3/library/argparse.html#nargs>`__.


Help texts
==========

Ticket :ticket:`985`.
I reworked the :mod:`lino.sphinxcontrib.help_text_builder` module
which starts to give first visible results.

I fixed a fundamental design flaw: there was only one target per
project doctree, but e.g. the doctree of :ref:`book` must write
:xfile:`help_texts.py` to both :mod:`lino.modlib.lino_startup` and
:mod:`lino_xl.lib.xl`.

I am still discovering the general workflow. It seems that it must
actually *not* be a builder but a perfectly normal extension which
just listens to the html builder and writes some additional files when
that builder finishes.

But for the moment the optimal execution order is this::

  $ pp inv bd bh initdb test

The most time-consuming part of this ticket is of course yet to do:
convert existing code to the new feature.



Developer's Guide
=================

:ref:`grigorij` reported more problems in
:ref:`lino.tutorial.writing_fixtures`.

The examples in this document were indeed very outdated and failed
completely.  I rewrote it completely, moved it to a directory on its
own and added test cases. Actually the filename "dumpy" should also 


AttributeError: 'module' object has no attribute 'chdir'
=========================================================

Build `439 <https://drone.io/github.com/lsaffre/lino/439>`__ fails on
drone.io with the following error::

    $ python --version
    Python 2.7.3
    $ pip --version
    pip 1.4.1 from /home/ubuntu/virtualenv/python2.7/lib/python2.7/site-packages (python 2.7)
    $ pip install -U setuptools
    Downloading/unpacking setuptools from https://pypi.python.org/packages/0a/f0/904432438dda1b4ed33c668392756bb45ae25a945458dd34d8215e68bdd7/setuptools-25.0.1.zip#md5=ce37e9e9f395a97fcf3ce3f1babb1f98
      Running setup.py egg_info for package setuptools
        Traceback (most recent call last):
          File "<string>", line 16, in <module>
          File "/home/ubuntu/virtualenv/python2.7/build/setuptools/setup.py", line 194, in <module>
            here and os.path.chdir(here)
        AttributeError: 'module' object has no attribute 'chdir'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/home/ubuntu/virtualenv/python2.7/build/setuptools/setup.py", line 194, in <module>

        here and os.path.chdir(here)

    AttributeError: 'module' object has no attribute 'chdir'


The same command on my machine works fine::

    $ pip install -U setuptools
    Collecting setuptools
      Downloading setuptools-25.1.0-py2.py3-none-any.whl (442kB)
        100% |████████████████████████████████| 450kB 532kB/s 
    Installing collected packages: setuptools
      Found existing installation: setuptools 20.6.7
        Uninstalling setuptools-20.6.7:
          Successfully uninstalled setuptools-20.6.7
    Successfully installed setuptools-25.1.0

I tried by inserting "pip install -U pip", now it seems to work.

For the moment I cannot see any explanation...
